#define R1GPIOBANK GPIOB
#define R2GPIOBANK GPIOG
#define R3GPIOBANK GPIOE
#define R4GPIOBANK GPIOE

#define C1GPIOBANK GPIOC
#define C2GPIOBANK GPIOC
#define C3GPIOBANK GPIOB
#define C4GPIOBANK GPIOC
#define C5GPIOBANK GPIOF

#define R1GPIOPIN GPIO_PIN_6
#define R2GPIOPIN GPIO_PIN_14
#define R3GPIOPIN GPIO_PIN_13
#define R4GPIOPIN GPIO_PIN_14

#define C1GPIOPIN GPIO_PIN_0
#define C2GPIOPIN GPIO_PIN_3
#define C3GPIOPIN GPIO_PIN_1
#define C4GPIOPIN GPIO_PIN_2
#define C5GPIOPIN GPIO_PIN_11
