M48
; DRILL file {KiCad 8.0.5} date 2024-11-21T04:34:33-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-21T04:34:33-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.295
%
G90
G05
T1
X125.2Y-164.675
X129.6Y-164.675
T2
X173.346Y-126.853
M30
