M48
; DRILL file {KiCad 8.0.5} date 2024-11-21T16:22:28-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-21T16:22:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.295
%
G90
G05
T1
X180.85Y-140.425
X185.25Y-140.425
T2
X228.996Y-102.603
M30
