M48
; DRILL file {KiCad 8.0.5} date 2024-11-21T16:33:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-21T16:33:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.388
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.600
%
G90
G05
T1
X113.91Y-119.49
X158.91Y-119.49
X166.66Y-87.58
T2
X107.46Y-119.49
X165.36Y-119.49
T3
X135.5Y-116.5
M30
